In [1]:
# ============================================================
# SpliceTransformer FINAL INFERENCE (MANUAL THRESHOLD)
# ============================================================

import os
import re
import json
import torch
import numpy as np
import pandas as pd
import importlib.util

from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from collections import Counter
from sklearn.metrics import confusion_matrix

# ================= CONFIG (TÙY CHỈNH TẠI ĐÂY) =================
MODEL_MAX_LEN = 8192
SEQ_LEN = 601
BATCH_SIZE = 64
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---- INFERENCE HYPERPARAMS ----
WINDOW_RADIUS = 25          # pooling ±25
TEMPERATURE = 0.7           # soften / sharpen probs

# 🔥 CẤU HÌNH NGƯỠNG (QUAN TRỌNG)
# Nếu True: Sử dụng ngưỡng cố định do bạn đặt (SPLICE_THRESHOLD).
# Nếu False: Sử dụng Top % như code cũ (TOP_SPLICE_RATIO).
USE_FIXED_THRESHOLD = True  

# Ngưỡng xác suất để chấp nhận là Splice site (0.0 -> 1.0)
# Ví dụ: 0.5 nghĩa là xác suất phải > 50% mới được coi là 1 hoặc 2. Nếu thấp hơn sẽ về 0.
# 0.00001
SPLICE_THRESHOLD = 0.00001 

# Cấu hình cũ (chỉ dùng khi USE_FIXED_THRESHOLD = False)
TOP_SPLICE_RATIO = 0.30     

# 🔥 Đảo ngược nhãn (True: 1->2, 2->1)
FIX_REVERSED_LABELS = True  

# ================= PATHS =================
DATA_DIR = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\data_gtex"
RESULT_DIR = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex"
CKPT_PATH = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\SpTransformer_pytorch.ckpt"
MODEL_CODE = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\SpliceTransformer-main\model\model.py"
METRICS_FILE = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\metrics.py"

os.makedirs(RESULT_DIR, exist_ok=True)

# ================= UTILS & DATASET =================
def load_module(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

class SpliceInferenceDataset(Dataset):
    def __init__(self, csv_path):
        self.df = pd.read_csv(csv_path)
        self.map = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
        self.pad_left = (MODEL_MAX_LEN - SEQ_LEN) // 2

    def __len__(self):
        return len(self.df)

    def encode_onehot(self, seq):
        onehot = np.zeros((4, len(seq)), dtype=np.float32)
        for i, c in enumerate(seq):
            if c in self.map:
                onehot[self.map[c], i] = 1.0
        return onehot

    def __getitem__(self, idx):
        seq = self.df.iloc[idx]["sequence"].upper().strip()
        label = int(self.df.iloc[idx]["Splicing_types"])
        if len(seq) == MODEL_MAX_LEN:
            x = self.encode_onehot(seq)
        elif len(seq) == SEQ_LEN:
            x = np.full((4, MODEL_MAX_LEN), 0.25, dtype=np.float32)
            onehot = self.encode_onehot(seq)
            x[:, self.pad_left:self.pad_left + SEQ_LEN] = onehot
        else:
            raise ValueError(f"Unexpected sequence length {len(seq)}")
        return torch.tensor(x), torch.tensor(label, dtype=torch.long)

# ================= LOAD MODEL =================
print("📦 Loading model & metrics...")
metrics_mod = load_module(METRICS_FILE, "metrics")
model_mod = load_module(MODEL_CODE, "model")

model = model_mod.SpTransformer(dim=128, tissue_num=15, attn_depth=6, max_seq_len=MODEL_MAX_LEN).to(DEVICE)
ckpt = torch.load(CKPT_PATH, map_location=DEVICE)
state_dict = ckpt.get("state_dict", ckpt)
state_dict = {k.replace("model.", ""): v for k, v in state_dict.items()}
model.load_state_dict(state_dict, strict=False)
model.eval()
print("✅ Model loaded")

# 1. Chỉ lấy các file bắt đầu bằng "gtex_test_" VÀ ngay sau đó là một con số (để tự động bỏ qua gtex_test_data.csv)
test_files = [f for f in os.listdir(DATA_DIR) if re.match(r"gtex_test_\d+", f)]

# 2. Sắp xếp dựa vào con số đầu tiên (vị trí index 2 sau khi split)
test_files = sorted(test_files, key=lambda x: int(x.split("_")[2]))

# ================= INFERENCE LOOP =================
for fname in test_files:
    ratio = fname.replace("gtex_test_", "").replace(".csv", "")
    print(f"\n🚀 Inference for ratio {ratio} | Threshold: {SPLICE_THRESHOLD if USE_FIXED_THRESHOLD else 'Top %'}")

    dataset = SpliceInferenceDataset(os.path.join(DATA_DIR, fname))
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False)

    all_labels, all_probs = [], []

    # 1. Chạy model lấy xác suất
    with torch.no_grad():
        for inputs, labels in tqdm(loader, desc=f"Running Model"):
            inputs = inputs.to(DEVICE)
            outputs = model(inputs)
            splice_logits = outputs[:, :3, :]
            
            # Pooling & Softmax
            center = splice_logits.shape[-1] // 2
            window = splice_logits[:, :, center-WINDOW_RADIUS:center+WINDOW_RADIUS+1]
            pooled_logits = torch.max(window, dim=2)[0]
            probs = torch.softmax(pooled_logits / TEMPERATURE, dim=1)

            all_labels.extend(labels.numpy())
            all_probs.extend(probs.cpu().numpy())

    all_labels = np.array(all_labels)
    all_probs = np.array(all_probs)

    # -------------------------------------------------------------
    # 🔥 FIX QUAN TRỌNG: Đảo cột xác suất NGAY TỪ ĐẦU
    # Lúc này Cột 1 = Acceptor Chính Xác, Cột 2 = Donor Chính Xác
    # -------------------------------------------------------------
    if FIX_REVERSED_LABELS:
        print("🔄 Swapping Probability Columns (1 <-> 2) to match Labels...")
        all_probs[:, [1, 2]] = all_probs[:, [2, 1]]
    
    # 2. Xử lý logic gán nhãn (Thresholding)
    all_preds = []
    
    # Tính ngưỡng (nếu dùng chế độ Percentile cũ)
    splice_scores = np.max(all_probs[:, 1:], axis=1) 
    
    if USE_FIXED_THRESHOLD:
        decision_threshold = SPLICE_THRESHOLD
    else:
        decision_threshold = np.percentile(splice_scores, 100 * (1 - TOP_SPLICE_RATIO))
        print(f"   ℹ️  Dynamic Threshold (Percentile {TOP_SPLICE_RATIO}): {decision_threshold:.4f}")

    # Vòng lặp quyết định nhãn từng mẫu
    for probs in all_probs:
        p_bg, p_acc, p_don = probs[0], probs[1], probs[2] 
        max_splice_prob = max(p_acc, p_don)

        # BƯỚC 1: So sánh với ngưỡng (Background vs Splice)
        if max_splice_prob < decision_threshold:
            pred = 0
        else:
            # BƯỚC 2: So sánh giữa Acc và Don
            # ⚠️ LƯU Ý: Vì all_probs đã được đảo cột ở trên rồi,
            # nên ở đây p_acc > p_don thì chắc chắn là lớp 1 (Acc).
            # KHÔNG cần đảo nhãn ở đây nữa!
            if p_acc > p_don:
                pred = 1 
            else:
                pred = 2
        
        all_preds.append(pred)

    all_preds = np.array(all_preds)

    print(f"📊 Prediction Stats: {Counter(all_preds)}")

    # ================= METRICS & CONFUSION MATRIX =================
    # Tính Confusion Matrix 3x3
    cm = confusion_matrix(all_labels, all_preds, labels=[0, 1, 2])
    print("\nConfusion Matrix:\n", cm)

    metrics = metrics_mod.compute_metrics(
        labels=all_labels,
        preds=all_preds,
        probs=all_probs,
        k=2
    )

    # ================= SAVE =================
    output = {
        "test_file": fname,
        "ratio": ratio,
        "config": {
            "window_radius": WINDOW_RADIUS,
            "temperature": TEMPERATURE,
            "use_fixed_threshold": USE_FIXED_THRESHOLD,
            "threshold_value": SPLICE_THRESHOLD if USE_FIXED_THRESHOLD else decision_threshold,
            "fix_reversed_labels": FIX_REVERSED_LABELS
        },
        "confusion_matrix": cm.tolist(),
        "metrics": metrics
    }

    out_path = os.path.join(RESULT_DIR, f"metrics_{ratio}.json")
    with open(out_path, "w") as f:
        json.dump(output, f, indent=4)

    print(f"💾 Saved → {out_path}")

print("\n🎉 DONE.")

📦 Loading model & metrics...
✅ Model loaded

🚀 Inference for ratio 1_1_1 | Threshold: 1e-05


Running Model: 100%|██████████| 646/646 [10:03<00:00,  1.07it/s]


🔄 Swapping Probability Columns (1 <-> 2) to match Labels...
📊 Prediction Stats: Counter({0: 14964, 1: 13228, 2: 13091})

Confusion Matrix:
 [[12360   787   629]
 [ 1346 12360    70]
 [ 1258    81 12392]]
💾 Saved → D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex\metrics_1_1_1.json

🚀 Inference for ratio 2_1_1 | Threshold: 1e-05


Running Model: 100%|██████████| 861/861 [13:26<00:00,  1.07it/s]


🔄 Swapping Probability Columns (1 <-> 2) to match Labels...
📊 Prediction Stats: Counter({0: 27283, 1: 14050, 2: 13726})

Confusion Matrix:
 [[24679  1610  1263]
 [ 1347 12359    70]
 [ 1257    81 12393]]
💾 Saved → D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex\metrics_2_1_1.json

🚀 Inference for ratio 4_1_1 | Threshold: 1e-05


Running Model: 100%|██████████| 1291/1291 [20:09<00:00,  1.07it/s]


🔄 Swapping Probability Columns (1 <-> 2) to match Labels...
📊 Prediction Stats: Counter({0: 52006, 1: 15675, 2: 14930})

Confusion Matrix:
 [[49401  3236  2467]
 [ 1348 12358    70]
 [ 1257    81 12393]]
💾 Saved → D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex\metrics_4_1_1.json

🚀 Inference for ratio 10_1_1 | Threshold: 1e-05


Running Model: 100%|██████████| 2583/2583 [40:10<00:00,  1.07it/s]


🔄 Swapping Probability Columns (1 <-> 2) to match Labels...
📊 Prediction Stats: Counter({0: 126060, 1: 20518, 2: 18689})

Confusion Matrix:
 [[123456   8079   6225]
 [  1347  12359     70]
 [  1257     80  12394]]
💾 Saved → D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex\metrics_10_1_1.json

🎉 DONE.


In [1]:
# ============================================================
# SpliceTransformer FINAL INFERENCE (SINGLE FILE VERSION)
# ============================================================

import os
import json
import torch
import numpy as np
import pandas as pd
import importlib.util

from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from collections import Counter
from sklearn.metrics import confusion_matrix

# ================= CONFIG (TÙY CHỈNH TẠI ĐÂY) =================
MODEL_MAX_LEN = 8192
SEQ_LEN = 601
BATCH_SIZE = 64
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---- INFERENCE HYPERPARAMS ----
WINDOW_RADIUS = 25          # pooling ±25
TEMPERATURE = 0.7           # soften / sharpen probs

# 🔥 CẤU HÌNH NGƯỠNG
USE_FIXED_THRESHOLD = True  
SPLICE_THRESHOLD = 0.00001 
TOP_SPLICE_RATIO = 0.30     

# 🔥 Đảo ngược nhãn (True: 1->2, 2->1)
FIX_REVERSED_LABELS = True  

# ================= PATHS =================
DATA_DIR = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\data_gtex"
RESULT_DIR = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex"
CKPT_PATH = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\SpTransformer_pytorch.ckpt"
MODEL_CODE = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\SpliceTransformer-main\model\model.py"
METRICS_FILE = r"D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\metrics.py"

# FILE CỤ THỂ CẦN CHẠY
TARGET_FILE = "gtex_test_100_1_1.csv"

os.makedirs(RESULT_DIR, exist_ok=True)

# ================= UTILS & DATASET =================
def load_module(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

class SpliceInferenceDataset(Dataset):
    def __init__(self, csv_path):
        self.df = pd.read_csv(csv_path)
        self.map = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
        self.pad_left = (MODEL_MAX_LEN - SEQ_LEN) // 2

    def __len__(self):
        return len(self.df)

    def encode_onehot(self, seq):
        onehot = np.zeros((4, len(seq)), dtype=np.float32)
        for i, c in enumerate(seq):
            if c in self.map:
                onehot[self.map[c], i] = 1.0
        return onehot

    def __getitem__(self, idx):
        seq = self.df.iloc[idx]["sequence"].upper().strip()
        label = int(self.df.iloc[idx]["Splicing_types"])
        if len(seq) == MODEL_MAX_LEN:
            x = self.encode_onehot(seq)
        elif len(seq) == SEQ_LEN:
            x = np.full((4, MODEL_MAX_LEN), 0.25, dtype=np.float32)
            onehot = self.encode_onehot(seq)
            x[:, self.pad_left:self.pad_left + SEQ_LEN] = onehot
        else:
            raise ValueError(f"Unexpected sequence length {len(seq)}")
        return torch.tensor(x), torch.tensor(label, dtype=torch.long)

# ================= LOAD MODEL =================
print("📦 Loading model & metrics...")
metrics_mod = load_module(METRICS_FILE, "metrics")
model_mod = load_module(MODEL_CODE, "model")

model = model_mod.SpTransformer(dim=128, tissue_num=15, attn_depth=6, max_seq_len=MODEL_MAX_LEN).to(DEVICE)
ckpt = torch.load(CKPT_PATH, map_location=DEVICE)
state_dict = ckpt.get("state_dict", ckpt)
state_dict = {k.replace("model.", ""): v for k, v in state_dict.items()}
model.load_state_dict(state_dict, strict=False)
model.eval()
print("✅ Model loaded")

# Kiểm tra file đích
full_path = os.path.join(DATA_DIR, TARGET_FILE)
if not os.path.exists(full_path):
    print(f"❌ KHÔNG TÌM THẤY FILE: {full_path}")
    exit()

# ================= INFERENCE LOOP (SINGLE FILE) =================
print(f"\n🚀 Running Inference for: {TARGET_FILE}")
print(f"   Threshold Mode: {'FIXED (' + str(SPLICE_THRESHOLD) + ')' if USE_FIXED_THRESHOLD else 'Top %'}")

dataset = SpliceInferenceDataset(full_path)
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False)

all_labels, all_probs = [], []

with torch.no_grad():
    for inputs, labels in tqdm(loader, desc="Processing"):
        inputs = inputs.to(DEVICE)
        outputs = model(inputs)
        splice_logits = outputs[:, :3, :]
        
        center = splice_logits.shape[-1] // 2
        window = splice_logits[:, :, center-WINDOW_RADIUS:center+WINDOW_RADIUS+1]
        pooled_logits = torch.max(window, dim=2)[0]
        probs = torch.softmax(pooled_logits / TEMPERATURE, dim=1)

        all_labels.extend(labels.numpy())
        all_probs.extend(probs.cpu().numpy())

all_labels = np.array(all_labels)
all_probs = np.array(all_probs)

# 🔥 FIX NHÃN ĐẢO NGƯỢC (Nếu cần)
if FIX_REVERSED_LABELS:
    print("🔄 Swapping Probability Columns (1 <-> 2) to match Labels...")
    all_probs[:, [1, 2]] = all_probs[:, [2, 1]]

# Logic gán nhãn
all_preds = []
splice_scores = np.max(all_probs[:, 1:], axis=1) 

if USE_FIXED_THRESHOLD:
    decision_threshold = SPLICE_THRESHOLD
else:
    decision_threshold = np.percentile(splice_scores, 100 * (1 - TOP_SPLICE_RATIO))
    print(f"ℹ️ Dynamic Threshold: {decision_threshold:.4f}")

for probs in all_probs:
    p_bg, p_acc, p_don = probs[0], probs[1], probs[2] 
    max_splice_prob = max(p_acc, p_don)

    if max_splice_prob < decision_threshold:
        pred = 0
    else:
        pred = 1 if p_acc > p_don else 2
    all_preds.append(pred)

all_preds = np.array(all_preds)

# ================= METRICS & SAVE =================
cm = confusion_matrix(all_labels, all_preds, labels=[0, 1, 2])
print("\n📊 Prediction Stats:", Counter(all_preds))
print("Confusion Matrix:\n", cm)

metrics = metrics_mod.compute_metrics(
    labels=all_labels,
    preds=all_preds,
    probs=all_probs,
    k=2
)

output = {
    "test_file": TARGET_FILE,
    "config": {
        "use_fixed_threshold": USE_FIXED_THRESHOLD,
        "threshold_value": float(decision_threshold)
    },
    "confusion_matrix": cm.tolist(),
    "metrics": metrics
}

out_name = f"metrics_{TARGET_FILE.replace('.csv', '')}.json"
out_path = os.path.join(RESULT_DIR, out_name)
with open(out_path, "w") as f:
    json.dump(output, f, indent=4)

print(f"\n✅ DONE. Result saved to: {out_path}")

📦 Loading model & metrics...
✅ Model loaded

🚀 Running Inference for: gtex_test_100_1_1.csv
   Threshold Mode: FIXED (1e-05)


Processing: 100%|██████████| 21920/21920 [5:27:39<00:00,  1.11it/s]  


🔄 Swapping Probability Columns (1 <-> 2) to match Labels...

📊 Prediction Stats: Counter({0: 1236531, 1: 90549, 2: 75777})
Confusion Matrix:
 [[1233870   78176   63304]
 [   1406   12295      75]
 [   1255      78   12398]]

✅ DONE. Result saved to: D:\Bio_sequence_Research_AITALAB\benchmark\task1_splicing_prediction\SpliceTransformer\results_gtex\metrics_gtex_test_100_1_1.json
